services:
  mt5:
    image: gmag11/metatrader5_vnc
    container_name: mt5_container
    volumes:
      - mt5_config:/config
    ports:
      - "3000:3000"
      - "8001:8001"
    environment:
      - CUSTOM_USER=admin
      - PASSWORD=admin123
    restart: unless-stopped

volumes:
  mt5_config:
